export enum GenderEnum {
  Male = 'male',
  Female = 'female',
}

export enum UserXHeaderNames {
  District = 'distrito',
  Identification = 'cedula',
  ClubAndCode = 'club_codigo',
  Birthday = 'birthday',
  Profession = 'profesion',
  Activity = 'actividad',
  MemberId = 'member_id',
  FullName = 'nombre_completo',
  Prefix = 'prefijo',
  FirstName = 'nombre',
  MiddleName = 'segundo_nombre',
  LastName = 'apellido',
  Suffix = 'sufijo',
  Gender = 'genero',
  Language = 'lenguaje',
  OriginalAdmissionDate = 'fecha_admision_original',
  AdmissionDate = 'fecha_admision',
  Affiliate = 'afiliacion',
  Registered = 'estado_inscripcion',
  SecondaryEmail = 'email_ingreso',
  Email = 'email_principal',
  CountryCode = 'country_code',
  Phone = 'telefono',
  AddressLine1 = 'direccion_fila_1',
  AddressLine2 = 'direccion_fila_2',
  AddressLine3 = 'direccion_fila_3',
  City = 'ciudad',
  State = 'estado',
  Province = 'provincia',
  Country = 'pais',
  PostalCode = 'codigo_postal',
  PostalStamp = 'etiqueta_postal',
}
